# Generated by Django 3.0.5 on 2020-09-22 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20200807_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
    ]
